pokec_z:
    nlayer: 3
    hidden_dim: 128
    filter_dim: 128
    epoch_fit: 300
    epoch_debias: 200
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    eigk: 256
    orthogonality: 10.0
    signal_dim: 128
    patience: 5
    label_number: 500
    sens_number: 200
pokec_n:
    nlayer: 2
    hidden_dim: 128
    filter_dim: 128
    epoch_fit: 0
    epoch_debias: 200
    lr: 0.001
    weight_decay: 0.0001
    tran_dropout: 0.3
    feat_dropout: 0.6
    prop_dropout: 0.6
    eigk: 64
    orthogonality: 100.0
    signal_dim: 128
    patience: 0
    label_number: 500
    sens_number: 200
credit:
    nlayer: 2
    hidden_dim: 128
    filter_dim: 128
    epoch_fit: 500
    epoch_debias: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    eigk: 128
    orthogonality: 500.0
    signal_dim: 128
    patience: 5
    label_number: 6000
    sens_number: -1
german:
    nlayer: 2
    hidden_dim: 128
    filter_dim: 4
    epoch_fit: 500
    epoch_debias: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    eigk: 128
    orthogonality: 200.0
    signal_dim: 128
    patience: 20
    label_number: 100
    sens_number: -1
bail:
    nlayer: 3
    hidden_dim: 128
    filter_dim: 128
    epoch_fit: 200
    epoch_debias: 500
    lr: 0.0002
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    eigk: 256
    orthogonality: 500.0
    signal_dim: 128
    patience: 0
    label_number: 100
    sens_number: -1
income:
    nlayer: 3
    hidden_dim: 64
    filter_dim: 64
    epoch_fit: 500
    epoch_debias: 500
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    eigk: 64
    orthogonality: 100.0
    signal_dim: 128
    patience: 5
    label_number: 3000
    sens_number: -1
